#!/usr/bin/env groovy

pipeline {
  options {
    timeout(time: 60, unit: 'MINUTES')
    ansiColor('xterm')
  }
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
   kube-worker: rustbuilder
spec:
  containers:
  - name: rust
    image: rust:alpine
    command:
    - cat
    tty: true
  - name: busybox
    image: busybox
    command:
    - cat
    tty: true
"""
    }
  }

  stages {
    stage('Setup') {
      steps {
        checkout scm
      }
    }
    stage('Build') {
      steps {
        script {
          echo sh(returnStdout: true, script: "cargo build")
        }
      }
    }
  }
}
