#!/usr/bin/env groovy

pipeline {
    options {
        timeout(time: 60, unit: 'MINUTES')
        ansiColor('xterm')
    }
    agent { 
        dockerfile {
            filename 'Dockerfile'
            dir '.'
            registryUrl 'https://hub.docker.com'
            registryCredentialsId 'dockerhub'
        }
    }
    stages {
        stage('Test') {
            steps {
                sh 'echo testing'
            }
        }
        stage('Push To Registry') {
            steps {
                script {
                    docker.build registry + ":$BUILD_NUMBER"
                }
            }
        }
    }
}
