name: Rust

on:
  push:
    branches:
      - master
      - releases/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose --manifest-path amortize
    - name: Run tests
      run: cargo test --verbose --manifest-path amortize
